trigger:
  branches:
    include:
      - main

pool:
  name: 'windows'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - task: npm@1
    inputs:
      command: 'install'
    displayName: 'Install dependencies'

  - task: npm@1
    inputs:
      command: 'run build'
    displayName: 'Build application'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'drop'
      publishLocation: 'Container'


