name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted  # Running on a self-hosted runner

    strategy:
      matrix:
        node-version: [18.x]  # Running tests or tasks on Node.js v18.x

    steps:
    - uses: actions/checkout@v3  # Check out the repository code
    - name: Use Node.js ${{ matrix.node-version }}  # Set up the correct Node.js version (18.x in this case)
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Uncomment the cache step if you want to cache npm dependencies for faster builds
        # cache: 'npm'
    - run: cd /var/www/actions-runner/actions-runner/_work/node-todo-cicd/node-todo-cicd && npm i  # Install backend dependencies
    - run: cd /var/www/actions-runner/actions-runner/_work/node-todo-cicd/node-todo-cicd && npm run build  # Run build command
    - run: pm2 restart 0  # Restart the Node.js application using PM2 (ensure PM2 is set up to manage your app)
    - run: sudo service nginx restart  # Restart Nginx to serve the updated content
