name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted  # Running on a self-hosted runner

    strategy:
      matrix:
        node-version: [18.x]  # Running tasks on Node.js v18.x

    steps:
    - uses: actions/checkout@v3  # Check out the repository code
    - name: Use Node.js ${{ matrix.node-version }}  # Set up the correct Node.js version (18.x in this case)
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Uncomment the cache step if you want to cache npm dependencies for faster builds
        # cache: 'npm'
    - name: Install backend dependencies
      run: cd node-todo-cicd && npm i  # Assuming 'node-todo-cicd' is a folder in the root of the repo
    - name: Build the backend
      run: cd node-todo-cicd && npm run build  # Run build command (Ensure the "build" script exists in package.json)
    - name: Restart the Node.js application using PM2
      run: pm2 restart 0  # Ensure PM2 is set up to manage your app
    - name: Restart Nginx to serve the updated content
      run: sudo service nginx restart  # Restart Nginx to serve the updated content
